# Generated by Django 5.1.7 on 2025-03-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField(default=0)),
                ('Quantity', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=10)),
                ('Category', models.CharField(max_length=100)),
                ('Date_Added', models.DateTimeField(auto_now=True)),
                ('Last_Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
