# Generated by Django 5.1.7 on 2025-03-29 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_user_alter_inventory_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='user',
        ),
        migrations.AddField(
            model_name='inventory',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inventory', to=settings.AUTH_USER_MODEL),
        ),
    ]
